/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatComponent: typeof import('./components/ChatComponent.vue')['default']
    ChatListPanel: typeof import('./components/ChatListPanel.vue')['default']
    ClickCopy: typeof import('./components/ClickCopy.vue')['default']
    Developer: typeof import('./components/Developer.vue')['default']
    DownLoadChatsList: typeof import('./components/DownLoadChatsList.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    QuestList: typeof import('./components/QuestList.vue')['default']
    WsChat: typeof import('./components/WsChat.vue')['default']
  }
}
