/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatComponent: typeof import('./components/ChatComponent.vue')['default']
    ChatListPanel: typeof import('./components/ChatListPanel.vue')['default']
    ClickCopy: typeof import('./components/ClickCopy.vue')['default']
    copy: typeof import('./components/WsChat copy.vue')['default']
    Developer: typeof import('./components/Developer.vue')['default']
    DownLoadChatsList: typeof import('./components/DownLoadChatsList.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HeadTip: typeof import('./components/HeadTip.vue')['default']
    IEpDArrowLeft: typeof import('~icons/ep/d-arrow-left')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpPointer: typeof import('~icons/ep/pointer')['default']
    IEpPosition: typeof import('~icons/ep/position')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    QuestList: typeof import('./components/QuestList.vue')['default']
    WsChat: typeof import('./components/WsChat.vue')['default']
    WsChatOther: typeof import('./components/WsChatOther.vue')['default']
  }
}
